export default {
    FORM_INVALID: "sign_in_invalid",
    FORM_INPUT: "sign_in_input",
    FORM_VALIDATE: "sign_in_validate",
    LOGOUT: "logout",
    ROUTER_GO: "go",
    ROUTER_REPLACE: "replace",
    INPUT_UPDATE_VALUE: "input_update_value",
    ROOM_UPDATE: "room_update",
    ROOMS_UPDATE: "rooms_update",
    USERS_UPDATE: "users_update",
    AVATAR_UPDATE: "avatar_update",
    NOTIFICATION_SHOW: "notification_show",
    CURRENT_CHAT_UPDATE: "current_chat_update",
    PROFILE_UPDATE_AVATAR: "profile_update_avatar",
    SEARCH_USERS: "search_users",
    CHAT_USER_ACTION: "chat_user_action",
    CREATE_CHAT: "create_chat",
    OPEN_ADD_USER_DIALOG: "open_add_user_dialog",
    OPEN_REMOVE_USER_DIALOG: "open_remove_user_dialog",
    CLOSE_DIALOG: "close_dialog",
    // Message events
    CREATE_CHAT_SESSION: "create_chat_session",
    CLOSE_CHAT_SESSION: "close_chat_session",
    SEND_MESSAGE: "send_message",
    MESSAGES_RECEIVED: "messages received",
    MESSAGES_UPDATE: "update_messages",
};
